name: RL Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  rl-check:
    name: Check ${{ matrix.folder }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        folder:
          - cat
          - cp
          - mv
          - rm
          - ls
          - echo
          - head
          - tail
          - grep
          - wc
          - rlsh
          - nano/src

    steps:
      - uses: actions/checkout@v4

      - name: Run RL check
        uses: rl-lang/rl-check@main
        with:
          folder: ${{ matrix.folder }}
          version: nightly